spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ''
    url: jdbc:postgresql://localhost:5432/todo
    username: ''
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false